
package com.mycompany;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NoSuchCountryException", targetNamespace = "http://gdp_service.mycompany.com/")
public class NoSuchCountryException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoSuchCountryException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public NoSuchCountryException_Exception(String message, NoSuchCountryException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public NoSuchCountryException_Exception(String message, NoSuchCountryException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.mycompany.NoSuchCountryException
     */
    public NoSuchCountryException getFaultInfo() {
        return faultInfo;
    }

}
